# Generated by Django 4.1.1 on 2022-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
    ]
